name: 'Validate SHACL'
description: 'This action will validate an RDF graph against a SHACL graph using pySHACL'
author: 'Konrad Höffner <konrad@gmx.at>'
inputs:
  data:
    description: 'The file containing the target data graph'
    required: true
  shacl:
    description: 'The file containing the SHACL Shapes graph'
    required: false
    default: shacl.ttl
  merge:
    description: 'Whether to merge the input files before validation if there are multiple.'
    required: false
    default: false
  inference:
    description: 'type of inferencing to run against the data graph before validating'
outputs:
  violations:
    description: 'Number of violations'
runs:
  using: 'docker'
  image: docker://ghcr.io/konradhoeffner/shacl:master
  args:
    - ${{ inputs.shacl }}
    - ${{ inputs.data }}
    - ${{ inputs.merge }}
    - ${{ inputs.inference }}
branding:
  icon: 'check-square'
  color: 'white'
