name: 'Validate SHACL'
description: 'This action will validate an RDF graph against a SHACL graph using pySHACL'
author: 'Konrad Höffner <konrad@gmx.at>'
inputs:
  data:
    description: 'The file containing the target data graph'
    required: true
  shacl:
    description: 'The file containing the SHACL Shapes graph'
    required: true
    default: shacl.ttl
  inference:
    description: 'type of inferencing to run against the data graph before validating'
outputs:
  violations:
    description: 'Number of violations'
    value: ${{ steps.validate.outputs.violations}}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v3
      if: ${{ !env.ACT }}
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install pySHACL
      run: pip install -r requirements.txt
      shell: bash
    - id: validate
      shell: bash {0}
      run: |
        log=$(pyshacl -a -s ${{ inputs.shacl}} ${{ inputs.data}})
        violations=$(grep -c 'Constraint Violation' <<< "$log")
        log="${log//'%'/'%25'}"
        log="${log//$'\n'/'%0A'}"
        log="${log//$'\r'/'%0D'}"
        if [[ "$violations" -gt 0 ]]; then echo "::warning ::$log"; fi
        echo $log
        echo "::set-output name=violations::$violations"
branding:
  icon: 'check-square'
  color: 'white'
