name: 'Validate SHACL'
description: 'This action will validate an RDF graph against a SHACL graph using pySHACL'
author: 'Konrad Höffner <konrad@gmx.at>'
inputs:
  shacl:
    description: 'The file containing the SHACL Shapes graph'
    required: false
    default: shacl.ttl
  data:
    description: 'The files containing the target data graph, separated by newlines'
    required: true
  inference:
    description: 'Type of inferencing to run against the data graph before validating'
outputs:
  violations:
    description: 'Number of violations'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - run: pip install 'pyshacl<2'
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh "${{ inputs.shacl }}" "${{ inputs.data }}" "${{ inputs.inference }}"
      shell: bash
branding:
  icon: 'check-square'
  color: 'white'
