name: 'Validate SHACL'
description: 'This action will validate an RDF graph against a SHACL graph using pySHACL'
author: 'Konrad Höffner <konrad@gmx.at>'
inputs:
  data:
    description: 'The file containing the target data graph'
    required: true
  shacl:
    description: 'The file containing the SHACL Shapes graph'
    required: false
    default: shacl.ttl
  inference:
    description: 'type of inferencing to run against the data graph before validating'
  image:
    description: 'The Docker image running pySHACL with the given inputs'
    required:  false
    default: ghcr.io/konradhoeffner/shacl@master
outputs:
  violations:
    description: 'Number of violations'
runs:
  using: 'docker'
  image: ${{ github.event.inputs.image }}
  args:
    - ${{ inputs.shacl }}
    - ${{ inputs.data }}
    - ${{ inputs.inference }}
    - ${{ inputs.image}}
branding:
  icon: 'check-square'
  color: 'white'
