name: test
 
on:
  workflow_dispatch:
  push:
    branches:
      - master
 
jobs:
  test-correct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test correct RDF graph
        uses: ./
        with:
          shacl: test/shacl.ttl
          data: test/data-correct.ttl
  test-incorrect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test incorrect RDF graph
        uses: ./
        with:
          shacl: test/shacl.ttl
          data: test/data-incorrect.ttl
