name: Test Action
 
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
 
jobs:
  test-correct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: This should succeed
        uses: ./
        with:
          shacl: test/shacl.ttl
          data: test/data-correct.ttl
  test-incorrect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: This should fail
        uses: ./
        with:
          shacl: test/shacl.ttl
          data: test/data-incorrect.ttl
