name: Test Action
 
on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request_target:
    branches: ['master']

jobs:
  test-correct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: This should succeed
        uses: ./
        with:
          shacl: test/shacl.ttl
          data: test/data-correct.ttl
  test-incorrect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: This should fail
        id: shacl-incorrect
        uses: ./
        continue-on-error: true
        with:
          shacl: test/shacl.ttl
          data: |
                test/data-correct.ttl
                test/data-incorrect.ttl
      - name: Invert success and failure
        run: if [[ ${{ steps.shacl-incorrect.outcome }} == "failure" ]]; then exit 0; else exit 1; fi
